# ===========================
# Application
# ===========================
spring.application.name=java-chatbot
server.port=8080

# ===========================
# Groq AI API
# ===========================
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.1-8b-instant
groq.api.max-tokens=1024

## ===========================
## HuggingFace Embedding API
## ======================ls -ltr
# =====
#huggingface.api.key=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
#huggingface.embedding.url=https://api-inference.huggingface.co/models/nomic-ai/nomic-embed-text-v1

# ===========================
# Pinecone Vector DB
# ===========================
pinecone.api.key=pcsk_6Gxn4e_H5v9pnHxziXBjeZCpUrrxm8UCnvR1ECC7WbQ3yyppgrcnh6SomRibuZdtNMZRGV
pinecone.index.url=https://astra-rag-index-1-vfeireg.svc.aped-4627-b74a.pinecone.io
pinecone.index.name=astra-rag-index-1

# ===========================
# RAG Config
# ===========================
rag.chunk.size=500
rag.chunk.overlap=50
rag.top.k=5

# ===========================
# Thymeleaf
# ===========================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===========================
# File Upload
# ===========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
